### ISSUE TITLE
This is no longer compatible with rider 2024.2 which is the latest version.

### ISSUE THREAD

**Issue by kkarnisky** [ellizio/odata-cli-ui#31]
This is no longer compatible with rider 2024.2 which is the latest version of rider.

**Comment by ellizio** [comment]
@kkarnisky Hello! 2024.2 has a few breaking changes in API. I need more time to migrate from 2024.1

**Comment by ellizio** [comment]
@kkarnisky update to 2024.2 has been released https://plugins.jetbrains.com/plugin/24117-odata-cli-ui/edit/versions/stable/591661 https://github.com/ellizio/odata-cli-ui/releases/tag/1.2.0-2024.2
